version: '2'
services:
    bcc-app:
        image: bcc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bcc-postgresql:5432/BCC
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bcc-postgresql:
        extends:
            file: postgresql.yml
            service: bcc-postgresql
